Fixes #4 - Add immutable remove operation
libp2p/go-libp2p-xor pull request #14
Opened 2021-06-22 11:49 UTC by xprazak2

2021-06-28 17:19 UTC, petar requested changes

2021-06-28 17:19 UTC, petar commented on trie/remove.go
> +	case trie.IsEmptyLeaf() || trie.IsNonEmptyLeaf():
If trie.IsEmptyLeaf(), you don't need to create a new empty leaf. You can just return the existing one.
You only need to create a new empty leaf if trie.IsNonEmptyLeaf(). So, split these two cases.

2021-06-28 17:19 UTC, petar commented on trie/remove.go
> +	case trie.IsEmptyLeaf() || trie.IsNonEmptyLeaf():
Furthermore, there is an important semantic point here. You want RemoveAtDepth to return the input trie, if no deletion happens. This will be used in the next function (below).

2021-06-28 17:19 UTC, petar commented on trie/remove.go
> +		copy := &Trie{}
We don't want to make a copy if the key being removed is not present,
i.e. if RemoveAtDepth(depth + 1, trie.Branch[dir], q) == trie.Branch[dir]

2021-07-04 10:09 UTC, xprazak2 commented
Thank you for your review, updated.

2021-07-06 16:17 UTC, petar requested changes
Code looks good now. Thank you! You need to run gofmt before we can submit.

2021-07-11 09:39 UTC, xprazak2 commented
Thanks, I updated the formatting.

2021-07-14 16:18 UTC, merged