Fixes #5 - Add union operation
libp2p/go-libp2p-xor pull request #15
Opened 2021-07-05 13:17 UTC by xprazak2

2021-07-14 21:57 UTC, petar requested changes
Good start.

2021-07-14 21:57 UTC, petar commented on trie/union.go
> +			return unionNonemptyLeaves(depth, left, right)
You don't need unionNonemptyLeaves. Use this:

	u := &Trie{}
	u.Add(depth, left.Key)
	u.Add(depth, right.Key)
	return u

Accordingly, get rid of

	func (trie *Trie) grow(depth int) *Trie[](url)

2021-07-14 21:57 UTC, petar commented on trie/union.go
> +func unionLeaf(depth int, trie, leaf *Trie) *Trie {
Call this unionTrieAndLeaf

2021-07-14 21:57 UTC, petar commented on trie/union.go
> +			return &Trie{Key: left.Key}
You need to make up your mind whether the result of UnionAtDepth reuses nodes (or subtries) from its inputs (left and right) or not. Here you are not reusing the node. But below in unionLeaf() you are reusing the input in "return trie".

2021-07-14 21:57 UTC, petar commented on trie/union.go
> +		return trie
Regarding my earlier comment: Here you are reusing nodes from the input of the union operation.

2021-07-18 13:22 UTC, xprazak2 commented on trie/union.go
> +			trie.Branch[1],
Should I clone the whole branches somehow?

2021-07-22 22:29 UTC, petar commented on trie/union.go
> +			trie.Branch[1],
It is very likely that both versions of union would be necessary in applications: a version that reuses the input tries (way faster, but immutable) and one that creates a new trie (slower, but mutable). I would add a boolean parameter to Union (and every other function that is called recursively) that specifies whether you want to reuse or not. E.g. you could call it "reuse bool".

Then, regarding your question here: Yes, Trie needs a Copy method. You can add one; should be pretty straightforward.

2021-08-03 06:18 UTC, xprazak2 commented on trie/union.go
> +			trie.Branch[1],
Thanks, I added a Copy method, Union should now always return a new trie.

2021-08-03 12:46 UTC, petar requested changes
One tiny change left.

2021-08-03 12:46 UTC, petar commented on trie/union.go
> +		return &Trie{Branch: [2]*Trie{
return trie.Copy()

2021-08-05 05:30 UTC, xprazak2 commented on trie/union.go
> +		return &Trie{Branch: [2]*Trie{
Thanks, updated.

2021-08-05 11:16 UTC, petar requested changes
Thanks for the update! I noticed that you also fixed a bug that evaded my eye. This made me think that before we submit this PR we should add a test that checks that the result of union does not reuse any of the nodes from its inputs. This seems particularly important as it will point the attention there to people who modify the code in the future. We should be good to go after that.

2021-08-10 06:07 UTC, xprazak2 commented
Thanks, I added a test to check for reused nodes.

2021-08-10 16:36 UTC, BigLep commented
@xprazak2 : @petar is away from the keyboard for a couple weeks.  We'll get this reviewed and ideally merged the week of 2021-08-26.

2021-08-23 06:25 UTC, petar requested changes

2021-08-23 06:25 UTC, petar commented on trie/union_test.go
> +	testTrieNotSameReference(t, expected, actual)
That's not the test we want. We want to check that "actual" does not share nodes with "left" or "right".
Here, you want something like:
testTrieNotSameReference(t, left, actual)
testTrieNotSameReference(t, right, actual)

And then testTrieNotSameReference would have to be re-implemented. You would need to put all the nodes of the "original" tree in a map[*Trie]bool. Then traverse all the nodes of "actual" and make sure they are not found in the map.

Furthermore, since there are always two inputs to a union, for efficiency, you don't want to make two separate calls to testTrieNotSameReference and build the map each time. So you might want to change its interface to:
testTrieNotSameReference(t *testing.T, left, right, union *Trie)

2021-09-01 05:56 UTC, xprazak2 commented on trie/union_test.go
> +	testTrieNotSameReference(t, expected, actual)
Thank you for a hint, updated.

2021-09-01 14:44 UTC, petar requested changes

2021-09-01 14:44 UTC, petar commented on trie/union_test.go
> +func testUnion(t *testing.T, sample *testSetSample) {
This looks good. It tests for not reusing nodes. But I think you dropped the test that verifies that  the union operation is correct. Add this:

expecting := FromKeys(UnionKeySlices(sample.LeftKeys, sample.RightKeys))
if !Equal(trie, expecting) {
   t.Errorf("union does not have expected values")
}

2021-09-05 09:04 UTC, xprazak2 commented on trie/union_test.go
> +func testUnion(t *testing.T, sample *testSetSample) {
I brought it back, thanks.

2021-09-06 16:15 UTC, petar approved these changes
LGTM

2021-09-06 16:16 UTC, merged

2021-09-06 16:17 UTC, petar commented
Thanks @xprazak2. This was a substantial feature!